### ISSUE TITLE
Resizing sponsor logos & adding to site

### ISSUE THREAD

**Issue by AnaFranciscaS** [humanmade/out-of-office#1]
Sponsor logos are coming in and they need to be resized and added to the site. 

In-kind sponsors & partner logos will remain in the top logo block (as it was previously) and ambassador and friends logos should be placed at the bottom of the homepage. Logos for ambassadors and friends should also be visibly smaller than the top tier logos. 

Logos are being [added here](https://drive.google.com/drive/u/0/folders/0B1JYiW9Rt7FkanVVNFVpbE5TWUU).

You can check sponsor levels in the ['Confirmed sponsors' tab here.](https://docs.google.com/spreadsheets/d/1fmzhIhevTXgNOKA5S5MSeiguevSqpj7KYeR38h18_ao/edit#gid=316133792).

**Comment by nomademoiselle** [comment]
I guess I can find all the logos in drive?

**Comment by AnaFranciscaS** [comment]
yep, link in issue ^

**Comment by nomademoiselle** [comment]
@AnaFranciscaS  Do we want all of our speakers company logos on the top logo block as well? I currently see 10 In-Kind Sponsors and 4 friends. I don't see a difference in the 4 friends where whether they are Top-Tier or not though?

**Comment by nomademoiselle** [comment]
Also, I only saw 6 logos in the Google drive. So I've resized these ones [here](https://drive.google.com/open?id=0BwgKJBk3Ug5IVHJHNEpCOWZnbEE) 

But there should be more logos, right? - could you make sure everything is there so I can bulk resize them all? I need to resize all the logos before starting to add them on the site to make sure it's all on the same ratio. 

I'm still a bit confused about exactly which logo needs to be on the top and which one needs to be in the friend's section. Also apparently there are different sizes/tiers as well?
 
In the spreadsheet, I've added one column mentioning **TOP** if in the top block or **nothing** if it's in the friend's section. The best would be if you could put all the logos for **top** in one folder on drive, and all other for the **friends** section in another folder. 

I'll be able to finish that on Monday since it will be the end of my day when you'll get in. But ping me anyway today when you get in so we can clarify it before I jump on this again. 

Thank ya!

**Comment by nomademoiselle** [comment]
What I understand: 

**Logos to be in the Top-block:**
These logos will be all the same size. 
- [x] Github (speaker)
- [x] Baremetric (speaker)
- [x] Human Made (speaker)
- [x] Hanno (Speaker)
- [x] Zapier (Speaker)
- [x] Lullabot (Speaker)
- [ ] Kavi Logo? (Speaker)

**Top Tiers**
- [ ] Remotive (Sponsor/Partner)
- [ ] Meet Edgar (Sponsor/Partner)
- [ ] Yonder (Sponsor/Partner)
- [ ] Crowdcast (Sponsor/Partner)
- [ ] Copass (Sponsor/Partner)
- [ ] WFH.io (Sponsor/Partner)
- [ ] Meet Edgar (Sponsor/Partner)

These logos are meant to be in the Top block section which looked like this in last year's website: 
<img width="1385" alt="screenshot 2017-04-21 11 42 52" src="https://cloud.githubusercontent.com/assets/14058946/25261986/bd156108-2687-11e7-9dac-80c7b7d17365.png">

Logos to be on the Friends/Ambassador section will be looking like the "resource for remoters" section we had in last year website. 
This will include: 

- [ ] Thomas 
- [ ] Jobpresso


**This means a total of 13 logos on the top block which is probably too much for the top block imho. 
I would suggest to only include the speakers' company logos on the top and then have a special section on the website for Top Tier Partners (big logos) and one for friends (small logos)**

**Comment by nomademoiselle** [comment]
done!
