### ISSUE TITLE
Videos to Youtube

### ISSUE THREAD

**Issue by AnaFranciscaS** [humanmade/out-of-office#15]
@nomademoiselle could you get the videos onto Youtube as you did last time, please? 

Let me know if you need anything from me.

**Comment by nomademoiselle** [comment]
Sure can do! I'll try to get them all in by the end of this week. 
Are we wanting an intro banner for each of them like last year?

**Comment by AnaFranciscaS** [comment]
Thanks, @nomademoiselle - yes please; exactly as you did last time would be perfect, with the HM event banner and their speaker banner. 

Just an FYI, I'm going to link people to our Youtube page (specifically the previous event playlist) when I send the follow-up email today. But will let them know it'll be on there soon etc

**Comment by nomademoiselle** [comment]
Update about this issue. 
- [x] Download videos from Crowdcast
- [x] Edit all videos - adding the HM intro and Speaker Banner to each of them
- [x] Export to .mov all the videos in OoO Google Drive
- [x] Upload videos to the HM Youtube channel in Private
- [ ] Setup the right youtube content and settings

Hey @AnaFranciscaS  the videos have been taking forever to upload to Youtube on my side... 😣 They are quite heavy files so it’s probably the reasons why it's been a pain. I’ve been having intermittent internet speed since Thursday and didn’t succeed at uploading them all to Youtube. I'm flying tomorrow to attend _Mind The Product_ and will be on Airport/Hotel wifi until Wednesday so it will probably be worst. If you would like to give it a try, [all the files are ready in Google Drive here.](https://drive.google.com/drive/u/0/folders/0BwgKJBk3Ug5IMFE3TzRCZjBpQTg)  

I'm happy to continue trying but I'm sure you want these files online sooner than later so let me know it's ok if I let you take it from here. 😊

**Comment by nomademoiselle** [comment]
Oh dear... just saw now that all my files in my local drive are not synced correctly! 😱
That's really annoying...  I'm going to bed now but I'm trying to sync them again and will try to figure out the problem in the morning if it's not solved by then.

**Comment by nomademoiselle** [comment]
@AnaFranciscaS All the videos are finally uploaded all to Youtube! Yay!!! 
I've also created a Playlist with all the out of office videos from 2017 in it. 
All is left to do now is adding the right content and change them to Public when ready. Let me know if you need anything else from me! :)

**Comment by AnaFranciscaS** [comment]
Whoop! Merci @nomademoiselle 🌷  I'm happy to add content and switch to public, will let you know in the next few days when that is done.

**Comment by AnaFranciscaS** [comment]
All added here: https://www.youtube.com/playlist?list=PL1H81eN4d97jZxE-s-cwNjbDD4B5_hZPR!
